fix: replace 'begrepsrelasjon' with correct properties according to s…
Informasjonsforvaltning/skos-ap-no-tools pull request #21
Opened 2022-03-31 13:09 UTC by oyvindis

Resolves #20 
Fixes according to spec: https://data.norge.no/specification/skos-ap-no-begrep/#Begrep_generiskRelasjon

2022-03-31 13:24 UTC, stigbd requested changes
bra jobba!

Einaste er å endre patch, så er vi good to go.

2022-03-31 13:24 UTC, stigbd commented on concept-builder/pom.xml
> +    <version>2.1.0</version>
Foreslår patch, dvs 2.0.1

2022-03-31 13:50 UTC, stigbd requested changes

2022-03-31 13:50 UTC, stigbd commented on concept-builder/src/test/resources/fasit.ttl
>                                    skosno:overordnetBegrep     <http://my.org/concept/Concept3> ;
`skosno:overordnetBegrep` -> `xkos:specializes`
Ref https://data.norge.no/specification/skos-ap-no-begrep/#GeneriskRelasjon_overordnetBegrep

2022-03-31 13:50 UTC, stigbd commented on concept-builder/src/test/resources/fasit.ttl
>                                    skosno:underordnetBegrep    <http://my.org/concept/Concept2> ;
`skosno:underordnetBegrep` -> `xkos:generalizes`
Ref https://data.norge.no/specification/skos-ap-no-begrep/#GeneriskRelasjon_underordnetBegrep

2022-03-31 13:50 UTC, stigbd commented on concept-builder/src/test/resources/fasit.ttl
>                                          skosno:assosiertBegrep  <http://my.org/concept/Concept2> ;
`skosno:assosiertBegrep` -> `skos:related`
Ref https://data.norge.no/specification/skos-ap-no-begrep/#AssosiativRelasjon_assosiertBegrep

2022-04-01 08:31 UTC, stigbd requested changes

2022-04-01 08:31 UTC, stigbd commented on concept-builder/src/test/resources/fasit.ttl
> +        skosno:partitivRelasjon [ a                           skosno:PartitivRelasjon ;
`skosno:partitiveRelasjon` -> `skosno:generiskRelasjon` og
`skosno:PartitivRelasjon` -> `skosno:GeneriskRelasjon`
Ref https://data.norge.no/specification/skos-ap-no-begrep/#_a_4_eksempler_p%C3%A5_generiske_relasjoner

2022-04-01 08:32 UTC, stigbd commented
Konsekvensen av siste endringsforlsag er at partitiv-eksempler faller ut av test-fila. Vi bør derfor lage nye eksempler som tester partitiv-relasjonen.

2022-04-04 07:53 UTC, stigbd approved these changes

2022-04-04 07:58 UTC, NilsOveTen approved these changes

2022-04-04 08:04 UTC, merged